import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Start Here',
      items: [
        'start-here/choose-your-path',
        'start-here/quickstart-java',
        'start-here/quickstart-spring-boot',
        'start-here/first-tool-call',
        'start-here/openai-compatible-and-trovebox',
        'start-here/feature-map',
        'start-here/why-ai4j',
      ],
    },
    {
      type: 'category',
      label: 'Core SDK',
      items: [
        'core-sdk/overview',
        'core-sdk/service-entry-and-registry',
        {
          type: 'category',
          label: 'Model Access',
          items: [
            'core-sdk/model-access/overview',
            'core-sdk/model-access/chat',
            'core-sdk/model-access/responses',
            'core-sdk/model-access/chat-vs-responses',
            'core-sdk/model-access/messages',
            'core-sdk/model-access/streaming',
            'core-sdk/model-access/multimodal',
            'core-sdk/model-access/request-and-response-conventions',
            'core-sdk/image-generation',
            'core-sdk/audio',
            'core-sdk/realtime',
          ],
        },
        {
          type: 'category',
          label: 'Tools and Skills',
          items: [
            'core-sdk/tools/overview',
            'core-sdk/tools/function-calling',
            'core-sdk/tools/annotation-based-tools',
            'core-sdk/tools/tool-execution-model',
            'core-sdk/tools/tool-whitelist-and-security',
            'core-sdk/skills/overview',
            'core-sdk/skills/discovery-and-loading',
            'core-sdk/skills/skill-vs-tool-vs-mcp',
          ],
        },
        {
          type: 'category',
          label: 'Memory and RAG',
          items: [
            'core-sdk/memory/overview',
            'core-sdk/memory/chat-memory',
            'core-sdk/memory/memory-and-tool-boundaries',
            'core-sdk/search-and-rag/overview',
            'core-sdk/search-and-rag/online-search',
            'core-sdk/search-and-rag/embedding',
            'core-sdk/search-and-rag/query-planning',
            'core-sdk/search-and-rag/rerank',
            'core-sdk/search-and-rag/vector-store-and-backends',
            'core-sdk/search-and-rag/ingestion-pipeline',
            'core-sdk/search-and-rag/chunking-strategies',
            'core-sdk/search-and-rag/hybrid-retrieval',
            'core-sdk/search-and-rag/citations-and-trace',
          ],
        },
      ],
    },
    {
      // MCP is a core capability-connection plane (client/transport/gateway/server),
      // not a Spring Boot / plugin integration — promoted to a top-level section.
      type: 'category',
      label: 'MCP',
      items: [
        'mcp/overview',
        'mcp/use-cases-and-paths',
        'core-sdk/mcp/protocol-capabilities',
        'mcp/client-integration',
        'mcp/transport-types',
        'mcp/streamable-http',
        'mcp/gateway-management',
        'mcp/configuration-and-gateway-reference',
        'mcp/third-party-mcp-integration',
        'mcp/tool-exposure-semantics',
        'mcp/build-your-mcp-server',
        'mcp/mcp-agent-end-to-end',
        'mcp/mysql-dynamic-datasource',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        {
          type: 'category',
          label: 'Spring Boot',
          items: [
            'spring-boot/overview',
            'spring-boot/quickstart',
            'spring-boot/auto-configuration',
            'spring-boot/configuration-reference',
            'spring-boot/bean-extension',
            'spring-boot/common-patterns',
          ],
        },
        {
          type: 'category',
          label: 'Extensions',
          items: [
            'core-sdk/extension/overview',
            'core-sdk/extension/plugin-packages',
            'core-sdk/extension/plugin-recipes',
            'core-sdk/extension/plugin-author-cookbook',
            'core-sdk/extension/ask-user-plugin',
            'core-sdk/extension/dynamic-workflow-plugin',
            'core-sdk/extension/provider-extension',
            'core-sdk/extension/model-extension',
            'core-sdk/extension/service-extension',
            'core-sdk/extension/spi-http-stack',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Agent Runtime',
      items: [
        'agent/overview',
        'agent/why-agent',
        'agent/quickstart',
        'agent/use-cases-and-paths',
        'agent/architecture',
        'agent/model-client-selection',
        'agent/provider-config-examples',
        'agent/tools-and-registry',
        'agent/skills',
        'agent/approval-permission-policy',
        'agent/memory-and-state',
        'agent/session-runtime',
        'agent/memory-compact-context',
        'agent/system-prompt-vs-instructions',
        'agent/plugin-lifecycle-hooks',
        'agent/sandbox-spi',
        'agent/cubesandbox-provider',
        'agent/agent-blueprint',
        {
          type: 'category',
          label: 'Runtimes and Orchestration',
          items: [
            'agent/minimal-react-agent',
            'agent/runtime-implementations',
            'agent/codeact-runtime',
            'agent/codeact-custom-sandbox',
            'agent/workflow-stategraph',
            'agent/subagent-handoff-policy',
            'agent/agent-teams',
            'agent/agent-teams-api-reference',
            'agent/weather-workflow-cookbook',
          ],
        },
        {
          type: 'category',
          label: 'Observability and Interoperability',
          items: [
            'agent/trace-observability',
            'agent/replay-recovery-audit',
            'agent/tool-interceptor',
            'agent/a2a',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Coding Agent',
      items: [
        'coding-agent/overview',
        'coding-agent/quickstart',
        'coding-agent/install-and-release',
        'coding-agent/cli-and-tui',
        'coding-agent/provider-profiles',
        'coding-agent/session-runtime',
        'coding-agent/tools-and-approvals',
        'coding-agent/sandbox-routing',
        'coding-agent/skills',
        'coding-agent/mcp-and-acp',
        'coding-agent/command-reference',
        {
          type: 'category',
          label: 'Architecture and Advanced Use',
          key: 'coding-agent-advanced',
          items: [
            'coding-agent/why-coding-agent',
            'coding-agent/architecture',
            'coding-agent/compact-and-checkpoint',
            'coding-agent/configuration',
            'coding-agent/runtime-architecture',
            'coding-agent/prompt-assembly',
            'coding-agent/mcp-integration',
            'coding-agent/acp-integration',
            'coding-agent/tui-customization',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FlowGram',
      items: [
        'flowgram/overview',
        'flowgram/quickstart',
        'flowgram/use-cases-and-paths',
        'flowgram/frontend-backend-integration',
        'flowgram/api-and-runtime',
        'flowgram/built-in-nodes',
        'flowgram/custom-nodes',
        'flowgram/agent-tool-knowledge-integration',
        {
          type: 'category',
          label: 'Architecture and Advanced Use',
          key: 'flowgram-advanced',
          items: [
            'flowgram/why-flowgram',
            'flowgram/architecture',
            'flowgram/runtime',
            'flowgram/workflow-execution-pipeline',
            'flowgram/custom-node-extension',
            'flowgram/frontend-custom-node-development',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Solutions',
      items: [
        'solutions/overview',
        'solutions/springboot-mysql-chat-memory',
        'solutions/springboot-jdbc-agent-memory',
        'solutions/rag-ingestion-vector-store',
        'solutions/deepseek-stream-search-rag',
        'solutions/legal-assistant',
        'solutions/flowgram-mysql-taskstore',
        'solutions/pinecone-vector-workflow',
        'solutions/searxng-web-search',
        'solutions/spi-dispatcher-connectionpool',
      ],
    },
    {
      type: 'category',
      label: 'Operate',
      items: [
        'security/overview',
        'operations/production-checklist',
        'troubleshooting/overview',
        'migration/overview',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'API & Versions',
          items: [
            'reference/api',
            'reference/version-compatibility',
            'reference/release-and-artifacts',
            'core-sdk/platform-service-matrix',
          ],
        },
        {
          type: 'category',
          label: 'Architecture & Maps',
          items: [
            'core-sdk/architecture-and-module-map',
            'core-sdk/package-map',
            'start-here/architecture-at-a-glance',
            'start-here/documentation-map',
            'agent/reference-core-classes',
          ],
        },
        {
          type: 'category',
          label: 'About',
          items: [
            'comparison/overview',
            'core-sdk/strengths-and-differentiators',
            'agent/sdk-roadmap',
            'faq',
            'glossary',
            'contributing',
          ],
        },
        {
          type: 'category',
          label: 'Maintainers',
          items: [
            'reference/release-checklist',
            'deploy/cloudflare-pages',
            'guides/blog-migration-map',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
