import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '快速开始',
      items: [
        'getting-started/installation',
        'getting-started/modules-and-maven-central',
        'getting-started/version-compatibility',
        'getting-started/platforms-and-service-matrix',
        'getting-started/quickstart-openai-jdk8',
        'getting-started/quickstart-springboot',
        'getting-started/spring-boot-autoconfiguration',
        'getting-started/quickstart-ollama',
        'getting-started/chat-and-responses-guide',
        'getting-started/multimodal-and-function-call',
        'getting-started/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Coding Agent',
      items: [
        'coding-agent/overview',
        'coding-agent/quickstart',
        'coding-agent/release-and-installation',
        'coding-agent/cli-and-tui',
        'coding-agent/runtime-architecture',
        'coding-agent/session-runtime',
        'coding-agent/compact-and-checkpoint',
        'coding-agent/prompt-assembly',
        'coding-agent/configuration',
        'coding-agent/provider-profiles',
        'coding-agent/tools-and-approvals',
        'coding-agent/skills',
        'coding-agent/mcp-integration',
        'coding-agent/acp-integration',
        'coding-agent/tui-customization',
        'coding-agent/command-reference',
      ],
    },
    {
      type: 'category',
      label: 'AI基础能力接入',
      items: [
        'ai-basics/overview',
        'ai-basics/architecture-and-package-map',
        'ai-basics/service-factory-and-registry',
        'ai-basics/unified-service-entry',
        'ai-basics/memory-and-tool-boundaries',
        'ai-basics/platform-adaptation',
        'ai-basics/request-and-response-conventions',
        'ai-basics/provider-and-model-extension',
        {
          type: 'category',
          label: 'Chat',
          items: [
            'ai-basics/chat/non-stream',
            'ai-basics/chat/stream',
            'ai-basics/chat/tool-calling',
            'ai-basics/chat/multimodal',
          ],
        },
        {
          type: 'category',
          label: 'Responses',
          items: [
            'ai-basics/responses/non-stream',
            'ai-basics/responses/stream-events',
            'ai-basics/responses/chat-vs-responses',
          ],
        },
        {
          type: 'category',
          label: '其它服务',
          items: [
            'ai-basics/services/embedding',
            'ai-basics/services/rerank',
            'ai-basics/services/audio',
            'ai-basics/services/image-generation',
            'ai-basics/services/realtime',
          ],
        },
        {
          type: 'category',
          label: '联网增强',
          items: [
            'ai-basics/online-search/overview',
            'ai-basics/online-search/searxng',
          ],
        },
        {
          type: 'category',
          label: 'RAG / 知识库增强',
          items: [
            'ai-basics/rag/overview',
            'ai-basics/rag/architecture-and-indexing',
            'ai-basics/rag/vector-store-and-storage-backends',
            'ai-basics/rag/ingestion-pipeline',
            'ai-basics/rag/chunking-strategies',
            'ai-basics/rag/hybrid-retrieval-and-rerank-workflow',
            'ai-basics/rag/citations-trace-and-ui-integration',
            'ai-basics/rag/pinecone-workflow',
          ],
        },
        {
          type: 'category',
          label: '网络栈扩展',
          items: [
            'ai-basics/enhancements/spi-http-stack',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'MCP',
      items: [
        'mcp/overview',
        'mcp/use-cases-and-paths',
        'mcp/configuration-and-gateway-reference',
        'mcp/transport-types',
        'mcp/client-integration',
        'mcp/third-party-mcp-integration',
        'mcp/gateway-management',
        'mcp/build-your-mcp-server',
        'mcp/mcp-agent-end-to-end',
        'mcp/tool-exposure-semantics',
        'mcp/mysql-dynamic-datasource',
      ],
    },
    {
      type: 'category',
      label: 'Agent 智能体',
      items: [
        'agent/overview',
        'agent/minimal-react-agent',
        'agent/use-cases-and-paths',
        'agent/system-prompt-vs-instructions',
        'agent/model-client-selection',
        'agent/custom-agent-development',
        'agent/runtime-implementations',
        'agent/memory-management',
        'agent/workflow-stategraph',
        'agent/codeact-runtime',
        'agent/codeact-custom-sandbox',
        'agent/subagent-handoff-policy',
        'agent/agent-teams',
        'agent/agent-teams-api-reference',
        'agent/trace-observability',
        'agent/weather-workflow-cookbook',
        'agent/reference-core-classes',
      ],
    },
    {
      type: 'category',
      label: 'Agentic 工作流平台',
      items: [
        'flowgram/overview',
        'flowgram/use-cases-and-paths',
        'flowgram/quickstart',
        'flowgram/api-and-runtime',
        'flowgram/frontend-backend-integration',
        'flowgram/workflow-execution-pipeline',
        'flowgram/frontend-custom-node-development',
        'flowgram/builtin-nodes',
        'flowgram/custom-node-extension',
        'flowgram/agent-tool-knowledge-integration',
      ],
    },
    {
      type: 'category',
      label: '场景实践',
      items: [
        'guides/springboot-mysql-chat-memory',
        'guides/springboot-jdbc-agent-memory',
        'guides/flowgram-mysql-taskstore',
        'guides/rag-ingestion-vector-store',
        'guides/deepseek-stream-search-rag',
        'guides/rag-legal-assistant',
        'guides/blog-migration-map',
      ],
    },
    {
      type: 'category',
      label: '部署',
      items: ['deploy/cloudflare-pages'],
    },
    'faq',
    'glossary',
  ],
};

export default sidebars;
