import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Start Here',
      items: [
        'start-here/why-ai4j',
        'start-here/architecture-at-a-glance',
        'start-here/choose-your-path',
        'start-here/quickstart-java',
        'start-here/quickstart-spring-boot',
        'start-here/first-chat',
        'start-here/first-tool-call',
        'start-here/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Core SDK',
      items: [
        'core-sdk/overview',
        'core-sdk/strengths-and-differentiators',
        'core-sdk/architecture-and-module-map',
        'core-sdk/package-map',
        'core-sdk/service-entry-and-registry',
        {
          type: 'category',
          label: 'Model Access',
          items: [
            'core-sdk/model-access/overview',
            'core-sdk/model-access/chat',
            'core-sdk/model-access/responses',
            'core-sdk/model-access/chat-vs-responses',
            'core-sdk/model-access/streaming',
            'core-sdk/model-access/multimodal',
            'core-sdk/model-access/request-and-response-conventions',
          ],
        },
        {
          type: 'category',
          label: 'Tools',
          items: [
            'core-sdk/tools/overview',
            'core-sdk/tools/function-calling',
            'core-sdk/tools/annotation-based-tools',
            'core-sdk/tools/tool-execution-model',
            'core-sdk/tools/tool-whitelist-and-security',
          ],
        },
        {
          type: 'category',
          label: 'Skills',
          items: [
            'core-sdk/skills/overview',
            'core-sdk/skills/discovery-and-loading',
            'core-sdk/skills/skill-vs-tool-vs-mcp',
          ],
        },
        {
          type: 'category',
          label: 'MCP',
          items: [
            'core-sdk/mcp/overview',
            'core-sdk/mcp/positioning-and-when-to-use',
            'core-sdk/mcp/protocol-capabilities',
            'core-sdk/mcp/client-integration',
            'core-sdk/mcp/gateway-and-multi-service',
            'core-sdk/mcp/transport-types',
            'core-sdk/mcp/publish-your-mcp-server',
            'core-sdk/mcp/third-party-mcp-integration',
            'core-sdk/mcp/tool-exposure-semantics',
          ],
        },
        {
          type: 'category',
          label: 'Memory',
          items: [
            'core-sdk/memory/overview',
            'core-sdk/memory/chat-memory',
            'core-sdk/memory/memory-and-tool-boundaries',
          ],
        },
        {
          type: 'category',
          label: 'Search & RAG',
          items: [
            'core-sdk/search-and-rag/overview',
            'core-sdk/search-and-rag/online-search',
            'core-sdk/search-and-rag/embedding',
            'core-sdk/search-and-rag/rerank',
            'core-sdk/search-and-rag/vector-store-and-backends',
            'core-sdk/search-and-rag/ingestion-pipeline',
            'core-sdk/search-and-rag/chunking-strategies',
            'core-sdk/search-and-rag/hybrid-retrieval',
            'core-sdk/search-and-rag/citations-and-trace',
          ],
        },
        {
          type: 'category',
          label: 'Extension',
          items: [
            'core-sdk/extension/overview',
            'core-sdk/extension/provider-extension',
            'core-sdk/extension/model-extension',
            'core-sdk/extension/service-extension',
            'core-sdk/extension/spi-http-stack',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Spring Boot',
      items: [
        'spring-boot/overview',
        'spring-boot/quickstart',
        'spring-boot/auto-configuration',
        'spring-boot/configuration-reference',
        'spring-boot/bean-extension',
        'spring-boot/common-patterns',
      ],
    },
    {
      type: 'category',
      label: 'Agent',
      items: [
        'agent/overview',
        'agent/why-agent',
        'agent/architecture',
        'agent/quickstart',
        'agent/model-client-selection',
        'agent/memory-and-state',
        'agent/tools-and-registry',
        {
          type: 'category',
          label: 'Runtimes',
          items: [
            'agent/runtimes/minimal-react-agent',
            'agent/runtimes/runtime-implementations',
            'agent/runtimes/codeact-runtime',
            'agent/runtimes/codeact-custom-sandbox',
          ],
        },
        {
          type: 'category',
          label: 'Orchestration',
          items: [
            'agent/orchestration/stategraph',
            'agent/orchestration/subagent-handoff',
            'agent/orchestration/teams',
            'agent/orchestration/teams-api-reference',
          ],
        },
        {
          type: 'category',
          label: 'Observability',
          items: [
            'agent/observability/trace',
          ],
        },
        'agent/reference-core-classes',
      ],
    },
    {
      type: 'category',
      label: 'Coding Agent',
      items: [
        'coding-agent/overview',
        'coding-agent/why-coding-agent',
        'coding-agent/quickstart',
        'coding-agent/install-and-release',
        'coding-agent/cli-and-tui',
        'coding-agent/architecture',
        'coding-agent/session-runtime',
        'coding-agent/compact-and-checkpoint',
        'coding-agent/configuration',
        'coding-agent/tools-and-approvals',
        'coding-agent/skills',
        'coding-agent/mcp-and-acp',
        'coding-agent/command-reference',
      ],
    },
    {
      type: 'category',
      label: 'Flowgram',
      items: [
        'flowgram/overview',
        'flowgram/why-flowgram',
        'flowgram/quickstart',
        'flowgram/architecture',
        'flowgram/runtime',
        'flowgram/frontend-backend-integration',
        'flowgram/built-in-nodes',
        'flowgram/custom-nodes',
        'flowgram/agent-tool-knowledge-integration',
      ],
    },
    {
      type: 'category',
      label: 'Solutions',
      items: [
        'solutions/overview',
        'solutions/springboot-mysql-chat-memory',
        'solutions/springboot-jdbc-agent-memory',
        'solutions/rag-ingestion-vector-store',
        'solutions/deepseek-stream-search-rag',
        'solutions/legal-assistant',
        'solutions/flowgram-mysql-taskstore',
        'solutions/pinecone-vector-workflow',
        'solutions/searxng-web-search',
        'solutions/spi-dispatcher-connectionpool',
      ],
    },
    {
      type: 'category',
      label: 'Deploy',
      items: ['deploy/cloudflare-pages'],
    },
    'faq',
    'glossary',
  ],
};

export default sidebars;
